Repository reactphp/dns, pull requests merged in 2019-07, with the labels that each got.

#127 Limit cache size to 256 results by default
  composer.json
  src/Query/RecordCache.php
  src/Resolver/Factory.php
  tests/Query/RecordCacheTest.php
Labels: new feature

#129 Implement `CachingExecutor` using cache TTL, deprecate old `CachedExecutor`
  src/Query/CachedExecutor.php
  src/Query/CachingExecutor.php
  src/Query/RecordBag.php
  src/Query/RecordCache.php
  src/Resolver/Factory.php
  tests/Query/CachingExecutorTest.php
  tests/Resolver/FactoryTest.php
Labels: bug, new feature

#130 Delete all deprecated APIs, use `Query` objects for `Message` questions instead of nested arrays and increase code coverage to 100%
  src/Config/FilesystemFactory.php
  src/Model/HeaderBag.php
  src/Model/Message.php
  src/Protocol/BinaryDumper.php
  src/Protocol/Parser.php
  src/Query/CachedExecutor.php
  src/Query/Executor.php
  src/Query/Query.php
  src/Query/RecordBag.php
  src/Query/RecordCache.php
  src/Resolver/Resolver.php
  tests/Config/ConfigTest.php
  tests/Config/FilesystemFactoryTest.php
  tests/Model/MessageTest.php
  tests/Protocol/BinaryDumperTest.php
  tests/Protocol/ParserTest.php
  tests/Query/CachedExecutorTest.php
  tests/Query/ExecutorTest.php
  tests/Query/HostsFileExecutorTest.php
  tests/Query/RecordBagTest.php
  tests/Query/RecordCacheTest.php
  tests/Query/RetryExecutorTest.php
  tests/Query/TimeoutExecutorTest.php
  tests/Resolver/ResolveAliasesTest.php
  tests/Resolver/ResolverTest.php
Labels: BC break, easy pick, maintenance

#132 Replace `HeaderBag` attributes with simple `Message` properties
  src/Model/HeaderBag.php
  src/Model/Message.php
  src/Protocol/BinaryDumper.php
  src/Protocol/Parser.php
  src/Query/CachingExecutor.php
  src/Query/UdpTransportExecutor.php
  src/Resolver/Resolver.php
  tests/Model/MessageTest.php
  tests/Protocol/BinaryDumperTest.php
  tests/Protocol/ParserTest.php
  tests/Query/CachingExecutorTest.php
  tests/Query/RetryExecutorTest.php
  tests/Query/UdpTransportExecutorTest.php
  tests/Resolver/ResolverTest.php
Labels: BC break, new feature

#133 Avoid garbage references when DNS resolution rejects on legacy PHP <= 5.6
  src/Query/CachingExecutor.php
  src/Query/CoopExecutor.php
  tests/FunctionalResolverTest.php
  tests/Query/CoopExecutorTest.php
Labels: new feature

#135 Move $nameserver from ExecutorInterface to UdpTransportExecutor
  README.md
  examples/91-query-a-and-aaaa.php
  examples/92-query-any.php
  src/Query/CachingExecutor.php
  src/Query/CoopExecutor.php
  src/Query/ExecutorInterface.php
  src/Query/HostsFileExecutor.php
  src/Query/RetryExecutor.php
  src/Query/TimeoutExecutor.php
  src/Query/UdpTransportExecutor.php
  src/Resolver/Factory.php
  src/Resolver/Resolver.php
  tests/Query/CachingExecutorTest.php
  tests/Query/CoopExecutorTest.php
  tests/Query/HostsFileExecutorTest.php
  tests/Query/RetryExecutorTest.php
  tests/Query/TimeoutExecutorTest.php
  tests/Query/UdpTransportExecutorTest.php
  tests/Resolver/FactoryTest.php
  tests/Resolver/ResolveAliasesTest.php
  tests/Resolver/ResolverTest.php
Labels: BC break, maintenance

#136 Mark all Record attributes as required, add documentation vs Query
  src/Model/Record.php
  src/Query/Query.php
  tests/Query/RetryExecutorTest.php
  tests/Resolver/ResolverTest.php
Labels: BC break, easy pick, maintenance

#138 Remove advanced/internal UdpTransportExecutor args (Parser/BinaryDumper)
  src/Query/UdpTransportExecutor.php
  tests/Query/UdpTransportExecutorTest.php
Labels: BC break, easy pick, maintenance

#134 Mark all classes as final to discourage inheritance
  src/BadServerException.php
  src/Config/Config.php
  src/Model/Message.php
  src/Model/Record.php
  src/Protocol/BinaryDumper.php
  src/Protocol/Parser.php
  src/Query/CachingExecutor.php
  src/Query/CancellationException.php
  src/Query/CoopExecutor.php
  src/Query/HostsFileExecutor.php
  src/Query/Query.php
  src/Query/RetryExecutor.php
  src/Query/TimeoutException.php
  src/Query/TimeoutExecutor.php
  src/Query/UdpTransportExecutor.php
  src/RecordNotFoundException.php
  src/Resolver/Factory.php
  src/Resolver/Resolver.php
Labels: BC break, easy pick, maintenance

#139 Add `ResolverInterface` as common interface for `Resolver` class
  README.md
  src/Resolver/Factory.php
  src/Resolver/Resolver.php
  src/Resolver/ResolverInterface.php
Labels: easy pick, maintenance, new feature

#140 Remove unneeded dependency on react/stream
  composer.json
Labels: easy pick, maintenance

#141 Support parsing CAA records
  examples/92-query-any.php
  src/Model/Message.php
  src/Model/Record.php
  src/Protocol/BinaryDumper.php
  src/Protocol/Parser.php
  tests/FunctionalResolverTest.php
  tests/Protocol/BinaryDumperTest.php
  tests/Protocol/ParserTest.php
Labels: new feature

#142 Support parsing SSHFP records
  examples/12-all-types.php
  examples/92-query-any.php
  src/Model/Message.php
  src/Model/Record.php
  src/Protocol/BinaryDumper.php
  src/Protocol/Parser.php
  tests/Protocol/BinaryDumperTest.php
  tests/Protocol/ParserTest.php
Labels: new feature

#143 Add missing private property definitions
  src/Config/HostsFile.php
  src/Query/UdpTransportExecutor.php
Labels: bug, easy pick, maintenance
