Repository reactphp/dns, pull requests merged in 2021-11, with the labels that each got.

#184 Support PHP 8.1
  .github/workflows/ci.yml
Labels: new feature, easy pick

#185 Avoid dependency on `ext-filter`
  src/Query/TcpTransportExecutor.php
  src/Query/UdpTransportExecutor.php
Labels: new feature

#186 Refactor `Parser` to avoid assigning dynamic properties (PHP 8.2+ compatibility)
  src/Protocol/Parser.php
Labels: new feature

#187 Skip invalid nameserver entries from `resolv.conf` and ignore IPv6 zone IDs
  src/Config/Config.php
  tests/Config/ConfigTest.php
Labels: bug, new feature
